# Generated by Django 5.2.4 on 2025-09-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_me'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Me',
        ),
    ]
