# Generated by Django 5.2.4 on 2025-09-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_delete_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('image', models.ImageField(upload_to='certificates/')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
